version: "3.9"
services:
  bookit-mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 3s
  bookit-backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SECRET=secret
      - MONGODB_URI=bookit-mongo
    links:
      - bookit-mongo
    depends_on:
      bookit-mongo:
        condition: service_healthy
  bookit-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.multistage
    ports:
      - "4100:80"
    links:
      - bookit-backend
    depends_on:
      - bookit-backend
