version: "3.9"

services:
  mongo:
    container_name: bookit-mongo
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 3s
  
  express-backend:
    container_name: bookit-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SECRET=secret
      - MONGODB_URI=bookit-mongo
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
  
  react-frontend:
    container_name: bookit-frontend
    build:
      context: ./frontend
    ports:
      - "4100:80"
    links:
      - express-backend
    depends_on:
      - express-backend
